#!/bin/sh

###############################################################################
# Script:  runIDV
#
# Purpose: script to launch the IDV
#
# Syntax:  runIDV <idv options>
#
# Notes:   In past versions of the IDV, users had to change this script to
# manipulate memory settings. The IDV now configures the  appropriate memory. 
# Users can also change the memory via the Preferences  menu. In exceptional 
# situations where the IDV may not start due to memory issues, it may be 
# necessary to bootstrap the memory size. In this case, please uncomment the 
# idv_memory section below and subsequently choose memory via the Preferences
# menu.  Be sure to comment it out that after setting the memory via the 
# Preferences if you want the preference to take effect. 
###############################################################################

##Error message, if needed.
error_msg="IDV failed to start. Please contact support-idv@unidata.ucar.edu"

dirname=`dirname $0`

java="java"
if test -f jre/bin/java; then
##We are in the installer directory
    java=./jre/bin/${java}
else
##Try using the dirname of this script
    if test -f ${dirname}/jre/bin/java; then
       java=${dirname}/jre/bin/${java}
    else 
       if test  ${JAVA_HOME}; then
##Try using JAVA_HOME
          java=${JAVA_HOME}/bin/${java}
       else 
##Try just using java
          java=${java}
      fi
    fi
fi

prefs="$(${java} -client -cp ${dirname}/idv.jar ucar.unidata.idv.IdvCommandLinePrefs $* 2>&1 )"

if [ $? -eq 1 ]; then
    echo "${error_msg}"
    exit 1
fi    

eval "${prefs}"

##Sanity check. If memory variable does not exist, we have problems
if test -z ${idv_memory}; then
    echo "${error_msg}"
    exit 1
fi

## See important note about this above. To bootstrap the IDV memory, uncomment 
## this line and set to a value  in megabytes. 
## idv_memory=512

## To avoid IDV crashes, in some situations it may be necessary to increase MaxPermSize. We have 
## especially noticed this problem on the OS X platform. The default MaxPermSize is 64m. To
## increase it to 128m please comment out next line and uncomment the following line.

## To avoid IDV OutOfMemory problems, it may be necessary to increase the MaxPermSize in the Java
## Virtual Machine. We have especially noticed this problem on the OS X platform. The default MaxPermSize
## is 64m. To increase it to 128m please comment out next line and uncomment the line following that. 

${java} -Xmx${idv_memory}m -Didv.enableStereo=false -jar ${dirname}/idv.jar $*
## ${java} -Xmx${idv_memory}m -XX:MaxPermSize=128m -Didv.enableStereo=false -jar ${dirname}/idv.jar $*