#!/bin/sh

java="java"
if test -f jre/bin/java; then
##We are in the installer directory
    java=./jre/bin/${java}
else
##Try using the dirname of this script
    if test -f ${dirname}/jre/bin/java; then
       java=${dirname}/jre/bin/${java}
    else 
       if test  ${JAVA_HOME}; then
##Try using JAVA_HOME
          java=${JAVA_HOME}/bin/${java}
       else 
##Try just using java
          java=${java}
      fi
    fi
fi

heap="$(${java} -cp idv.jar ucar.unidata.idv.UserMemory  2>&1 )"

dirname=`dirname $0`
command="${java} -Xmx${heap}m -Didv.enableStereo=false -jar ${dirname}/idv.jar $*"

${command}

