#!/bin/sh

##Error message, if needed.
error_msg="IDV failed to start. Please contact support-idv@unidata.ucar.edu"

java="java"
if test -f jre/bin/java; then
##We are in the installer directory
    java=./jre/bin/${java}
else
##Try using the dirname of this script
    if test -f ${dirname}/jre/bin/java; then
       java=${dirname}/jre/bin/${java}
    else 
       if test  ${JAVA_HOME}; then
##Try using JAVA_HOME
          java=${JAVA_HOME}/bin/${java}
       else 
##Try just using java
          java=${java}
      fi
    fi
fi

prefs="$(${java} -client -cp idv.jar ucar.unidata.idv.IdvCommandLinePrefs $* 2>&1 )"

if [ $? -eq 1 ]; then
    echo "IDV failed to start. Please contact support-idv@unidata.ucar.edu"
    exit 1
fi    

eval "${prefs}"

##Sanity check. If memory variable does not exist, we have problems
if test -z ${idv_memory}; then
    echo "IDV failed to start. Please contact support-idv@unidata.ucar.edu"
    exit 1
fi

dirname=`dirname $0`
${java} -Xmx${idv_memory}m -Didv.enableStereo=false -jar ${dirname}/idv.jar $*